# Generated by Django 4.0.4 on 2022-04-23 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_movie_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('total_seasons', models.IntegerField()),
                ('year', models.CharField(max_length=9)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('awards', models.CharField(max_length=255)),
                ('poster_url', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('votes', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_movie', to='core.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_movie_episode_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=9)),
                ('released', models.DateField()),
                ('episode_number', models.IntegerField()),
                ('season', models.IntegerField()),
                ('runtime', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('awards', models.CharField(max_length=255)),
                ('poster_url', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('votes', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.movie')),
            ],
        ),
    ]
