version: "3.9"

services:
    app:
        container_name: angular
        image: angular
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
